port: 5000
database:
  host: localhost
  port: 15432
  username: postgres
  password: 123456
  database: postgres
  sslMode: disable
telegram:
  enabled: false
  apiToken:
  chatId:
  sendErrors:
jwtKey: my_secret_key1
